import Head from "next/head";
import Alert from "@/components/Alert";
import Header from "@/components/Header";
import List from "@/components/List";
import { type NextPage } from "next";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Amatime</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen md:max-w-screen-md md:mx-auto space-y-2 p-4">
        <Header />
        <main className="space-y-2 bg-white">
          <Alert message="This is a message..." />
          <List />
        </main>
        <footer className="flex flex-row justify-center items-center gap-4 border p-4 bg-white">
          <h2 className="text-2xl font-medium">Footer</h2>
        </footer>
      </div>
    </>
  );
};

export default Home;
